### ISSUE TITLE
Links in the footer

### ISSUE THREAD

**Issue by davidcusack** [bcgov/bootstrap-theme#19]
Hi,

Is there a reason the links in the footer use the human readable links and not the guids?

Thanks,
David

**Comment by andrewwhitehead** [comment]
I don't know what this is referring to.

**Comment by davidcusack** [comment]
Hi,

All of the links in the footers are using the human readable links.
For example the disclaimer is using https://www2.gov.bc.ca/gov/content/home/disclaimer, when it should be using the GUID version https://www2.gov.bc.ca/gov/content?id=79F93E018712422FBC8E674A67A70535. That way if the page is moved the link never breaks.

**Comment by andrewwhitehead** [comment]
Thanks. Is that documented somewhere?

**Comment by davidcusack** [comment]
Yup. It’s in the writer’s guide here under Best Practices
https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/web-content-development-guides/writing-for-the-web/web-style-guide/links

David Cusack
User Experience Design Lead / Web Team Manager
Stakeholder Relations / Ministry of Education
778-679-2382 / david.cusack@gov.bc.ca

**Comment by andrewwhitehead** [comment]
Yes but what are the UUID links we're supposed to be using? gov.bc.ca is using the human readable links.

**Comment by davidcusack** [comment]
Disclaimer - https://www2.gov.bc.ca/gov/content?id=79F93E018712422FBC8E674A67A70535
Privacy - https://www2.gov.bc.ca/gov/content?id=9E890E16955E4FF4BF3B0E07B4722932
Accessibility - https://www2.gov.bc.ca/gov/content?id=E08E79740F9C41B9B0C484685CC5E412
Copyright - https://www2.gov.bc.ca/gov/content?id=1AAACC9C65754E4D89A118B875E0FBDA
Contact Us - https://www2.gov.bc.ca/gov/content?id=6A77C17D0CCB48F897F8598CCC019111

You can get the GUID for any page, but clicking on the floating icon in the bottom right hand corner of the page.

**Comment by juhewitt** [comment]
Some historical context, @davidcusack we'd have to check dates, but that may have been in place when they did the HRU implementation to redirect to the GUID, and they did so for that reason.  It's worth chatting with them about changing to them to the GUID.  As long as that resource stays consistant, you should be good... in addition, it's worth asking if they created short urls for these... b/c they may have... Comp Sci 101... why have 1, when you can have 3!!!??? :)
