### ISSUE TITLE
Default body font size is 16px?

### ISSUE THREAD

**Issue by GregTurner** [bcgov/bootstrap-theme#6]
Bootstrap bumped up default font size from 14px in v3 to 16px in v4.  And for good reasons:

> For a more inclusive and accessible type scale, we assume the browser default root font-size (typically 16px) so visitors can customize their browser defaults as needed.

However, the [B.C. Gov-look-feel 2.0](http://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/web-content-development-guides/developers-guide/css-elements) says 14px.  

The good news is that's easy to change our minds if we want the bigger base font size.

@juhewitt what's your thoughts on this?

**Comment by juhewitt** [comment]
Allo!  I'll check in with our UX research we conducted very recently.  It spoke of the same story, but there was a font-size that was discussed and I want to align with them.  Should hear shortly.

**Comment by dlevineBC** [comment]
@juhewitt @GregTurner We found evidence in our research that the font size was too small. Gillian can speak to this more. We also just know from general web standards and accessibility that the font size needs to increase.

**Comment by GregTurner** [comment]
You should know, that v4 uses `rem` sizing instead of `px` sizing.  Apparently this is better for devices and accessibility because the browser (aka user-agent) can set this on each device.

> This means that 1rem equals the font size of the html element (which for most browsers has a default value of 16px).

**Comment by juhewitt** [comment]
I'm with you all the way. rem is correct over the px sizing.  the default of 16px for browsers I'm fine with.  it's really a communications piece now @GregTurner, as this will be the first iteration with changes (even if minor) to all layouts... updating guides etc...

**Comment by GregTurner** [comment]
@juhewitt sounds like I should proceed with 1rem sizing (16px in practice)?

**Comment by juhewitt** [comment]
I've discussed with a few folks around here, including the product owner of gov.bc.ca, and if the open source community states this is best practice after years of deliberation, the I see no reason as to why we wouldn't comply. 👍

**Comment by GregTurner** [comment]
Thanks for the support @juhewitt.

**Comment by GregTurner** [comment]
Thanks for the support @juhewitt
